///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String ic_launcher = 'assets/ic_launcher.png';
  static const String ic_launcher_48 = 'assets/ic_launcher_48.png';
  static const String ic_launcher_72 = 'assets/ic_launcher_72.png';
  static const String ic_launcher_96 = 'assets/ic_launcher_96.png';
  static const String ic_launcher_144 = 'assets/ic_launcher_144.png';
  static const String voice = 'assets/voice.png';
  static const String google = 'assets/google.png';
  static const String twitter = 'assets/twitter.png';
  static const String facebook = 'assets/facebook.png';
  static const String like = 'assets/like.png';
  static const String liked = 'assets/liked.png';
  static const String read = 'assets/read.png';
  static const String comment = 'assets/comment.png';
}
